language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

# command to run tests
script:
  - nosetests --with-coverage # Add me to run nose with coverage support.

after_success:
  - coveralls
